Repository emberjs/ember-legacy-controllers, pull requests merged in 2020-05, with the labels that each got.

#10 Fixes
  .editorconfig
  .gitignore
  .npmignore
  .travis.yml
  .watchmanconfig
  CONTRIBUTING.md
  addon/array.js
  app/initializers/ember-legacy-controllers.js
  bower.json
  config/ember-try.js
  ember-cli-build.js
  index.js
  package.json
  testem.js
  testem.json
  tests/dummy/app/app.js
  tests/dummy/app/index.html
  tests/dummy/config/environment.js
  tests/helpers/resolver.js
  tests/index.html
  tests/test-helper.js
  tests/unit/array-test.js
  tests/unit/item-controller-class-test.js
  tests/unit/utils/sortable-mixin-test.js
  vendor/.gitkeep
  vendor/legacy-each-view-item-controller-support/index.js
  yarn.lock
Labels: breaking, bug

#11 Fix legacy each with item controller
  app/.gitkeep
  app/controllers/array.js
  app/controllers/object.js
  tests/integration/legacy-each-view-test.js
  vendor/legacy-each-view-item-controller-support/index.js
Labels: bug

#12 Add release automation setup.
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
